# Generated by Django 3.2.4 on 2021-07-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210724_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='on_order',
            new_name='in_order',
        ),
    ]
